<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Endpoint;

class PatchSignatureRequestsSignatureRequestIdSignersSignerId extends \IIYousign\Runtime\Client\BaseEndpoint implements \IIYousign\Runtime\Client\Endpoint
{
    use \IIYousign\Runtime\Client\EndpointTrait;
    protected $signerId;
    protected $signatureRequestId;

    /**
     * Update a signer.
     *
     * @param string $signerId           Signer id
     * @param string $signatureRequestId Signature request id
     */
    public function __construct(string $signerId, string $signatureRequestId, ?\IIYousign\Model\SignatureRequestsSignatureRequestIdSignersSignerIdPatchBody $requestBody = null)
    {
        $this->signerId = $signerId;
        $this->signatureRequestId = $signatureRequestId;
        $this->body = $requestBody;
    }

    public function getMethod(): string
    {
        return 'PATCH';
    }

    public function getUri(): string
    {
        return str_replace(['{signerId}', '{signatureRequestId}'], [$this->signerId, $this->signatureRequestId], '/signature_requests/{signatureRequestId}/signers/{signerId}');
    }

    public function getBody(\Symfony\Component\Serializer\SerializerInterface $serializer, $streamFactory = null): array
    {
        if ($this->body instanceof \IIYousign\Model\SignatureRequestsSignatureRequestIdSignersSignerIdPatchBody) {
            return [['Content-Type' => ['application/json']], $serializer->serialize($this->body, 'json')];
        }

        return [[], null];
    }

    public function getExtraHeaders(): array
    {
        return ['Accept' => ['application/json']];
    }

    /**
     * {@inheritdoc}
     *
     * @return \IIYousign\Model\Signer
     *
     * @throws \IIYousign\Exception\PatchSignatureRequestsSignatureRequestIdSignersSignerIdBadRequestException
     * @throws \IIYousign\Exception\PatchSignatureRequestsSignatureRequestIdSignersSignerIdUnauthorizedException
     * @throws \IIYousign\Exception\PatchSignatureRequestsSignatureRequestIdSignersSignerIdForbiddenException
     * @throws \IIYousign\Exception\PatchSignatureRequestsSignatureRequestIdSignersSignerIdNotFoundException
     * @throws \IIYousign\Exception\UnexpectedStatusCodeException
     */
    protected function transformResponseBody(string $body, int $status, \Symfony\Component\Serializer\SerializerInterface $serializer, ?string $contentType = null)
    {
        if (is_null($contentType) === false && (200 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            return $serializer->deserialize($body, 'IIYousign\\Model\\Signer', 'json');
        }
        if (is_null($contentType) === false && (400 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \IIYousign\Exception\PatchSignatureRequestsSignatureRequestIdSignersSignerIdBadRequestException($serializer->deserialize($body, 'IIYousign\\Model\\ResponseBadRequestError', 'json'));
        }
        if (is_null($contentType) === false && (401 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \IIYousign\Exception\PatchSignatureRequestsSignatureRequestIdSignersSignerIdUnauthorizedException($serializer->deserialize($body, 'IIYousign\\Model\\ResponseUnauthorizedError', 'json'));
        }
        if (is_null($contentType) === false && (403 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \IIYousign\Exception\PatchSignatureRequestsSignatureRequestIdSignersSignerIdForbiddenException();
        }
        if (is_null($contentType) === false && (404 === $status && mb_strpos($contentType, 'application/json') !== false)) {
            throw new \IIYousign\Exception\PatchSignatureRequestsSignatureRequestIdSignersSignerIdNotFoundException();
        }
        throw new \IIYousign\Exception\UnexpectedStatusCodeException($status, $body);
    }

    public function getAuthenticationScopes(): array
    {
        return ['bearerAuth'];
    }
}
