<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Normalizer;

use IIYousign\Runtime\Normalizer\CheckArray;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ConsumptionsGetResponse200AppNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;

    public function supportsDenormalization($data, $type, $format = null): bool
    {
        return $type === 'IIYousign\\Model\\ConsumptionsGetResponse200App';
    }

    public function supportsNormalization($data, $format = null): bool
    {
        return is_object($data) && get_class($data) === 'IIYousign\\Model\\ConsumptionsGetResponse200App';
    }

    /**
     * @return mixed
     */
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \IIYousign\Model\ConsumptionsGetResponse200App();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('electronic_signature', $data)) {
            $object->setElectronicSignature($data['electronic_signature']);
        }
        if (\array_key_exists('advanced_electronic_signature', $data)) {
            $object->setAdvancedElectronicSignature($data['advanced_electronic_signature']);
        }
        if (\array_key_exists('advanced_electronic_signature_with_qualified_certificate', $data)) {
            $object->setAdvancedElectronicSignatureWithQualifiedCertificate($data['advanced_electronic_signature_with_qualified_certificate']);
        }

        return $object;
    }

    /**
     * @return array|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        if (null !== $object->getElectronicSignature()) {
            $data['electronic_signature'] = $object->getElectronicSignature();
        }
        if (null !== $object->getAdvancedElectronicSignature()) {
            $data['advanced_electronic_signature'] = $object->getAdvancedElectronicSignature();
        }
        if (null !== $object->getAdvancedElectronicSignatureWithQualifiedCertificate()) {
            $data['advanced_electronic_signature_with_qualified_certificate'] = $object->getAdvancedElectronicSignatureWithQualifiedCertificate();
        }

        return $data;
    }
}
