<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Normalizer;

use IIYousign\Runtime\Normalizer\CheckArray;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ConsumptionsGetResponse200Normalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;

    public function supportsDenormalization($data, $type, $format = null): bool
    {
        return $type === 'IIYousign\\Model\\ConsumptionsGetResponse200';
    }

    public function supportsNormalization($data, $format = null): bool
    {
        return is_object($data) && get_class($data) === 'IIYousign\\Model\\ConsumptionsGetResponse200';
    }

    /**
     * @return mixed
     */
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \IIYousign\Model\ConsumptionsGetResponse200();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('app', $data)) {
            $object->setApp($this->denormalizer->denormalize($data['app'], 'IIYousign\\Model\\ConsumptionsGetResponse200App', 'json', $context));
        }
        if (\array_key_exists('api', $data)) {
            $object->setApi($this->denormalizer->denormalize($data['api'], 'IIYousign\\Model\\ConsumptionsGetResponse200Api', 'json', $context));
        }
        if (\array_key_exists('connector', $data)) {
            $object->setConnector($this->denormalizer->denormalize($data['connector'], 'IIYousign\\Model\\ConsumptionsGetResponse200Connector', 'json', $context));
        }

        return $object;
    }

    /**
     * @return array|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        if (null !== $object->getApp()) {
            $data['app'] = $this->normalizer->normalize($object->getApp(), 'json', $context);
        }
        if (null !== $object->getApi()) {
            $data['api'] = $this->normalizer->normalize($object->getApi(), 'json', $context);
        }
        if (null !== $object->getConnector()) {
            $data['connector'] = $this->normalizer->normalize($object->getConnector(), 'json', $context);
        }

        return $data;
    }
}
