<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Normalizer;

use IIYousign\Runtime\Normalizer\CheckArray;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class ContactNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;

    public function supportsDenormalization($data, $type, $format = null): bool
    {
        return $type === 'IIYousign\\Model\\Contact';
    }

    public function supportsNormalization($data, $format = null): bool
    {
        return is_object($data) && get_class($data) === 'IIYousign\\Model\\Contact';
    }

    /**
     * @return mixed
     */
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \IIYousign\Model\Contact();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('id', $data)) {
            $object->setId($data['id']);
        }
        if (\array_key_exists('first_name', $data)) {
            $object->setFirstName($data['first_name']);
        }
        if (\array_key_exists('last_name', $data)) {
            $object->setLastName($data['last_name']);
        }
        if (\array_key_exists('email', $data)) {
            $object->setEmail($data['email']);
        }
        if (\array_key_exists('locale', $data)) {
            $object->setLocale($data['locale']);
        }
        if (\array_key_exists('phone_number', $data) && $data['phone_number'] !== null) {
            $object->setPhoneNumber($data['phone_number']);
        } elseif (\array_key_exists('phone_number', $data) && $data['phone_number'] === null) {
            $object->setPhoneNumber(null);
        }
        if (\array_key_exists('company_name', $data) && $data['company_name'] !== null) {
            $object->setCompanyName($data['company_name']);
        } elseif (\array_key_exists('company_name', $data) && $data['company_name'] === null) {
            $object->setCompanyName(null);
        }
        if (\array_key_exists('job_title', $data) && $data['job_title'] !== null) {
            $object->setJobTitle($data['job_title']);
        } elseif (\array_key_exists('job_title', $data) && $data['job_title'] === null) {
            $object->setJobTitle(null);
        }
        if (\array_key_exists('address_line_1', $data) && $data['address_line_1'] !== null) {
            $object->setAddressLine1($data['address_line_1']);
        } elseif (\array_key_exists('address_line_1', $data) && $data['address_line_1'] === null) {
            $object->setAddressLine1(null);
        }
        if (\array_key_exists('address_line_2', $data) && $data['address_line_2'] !== null) {
            $object->setAddressLine2($data['address_line_2']);
        } elseif (\array_key_exists('address_line_2', $data) && $data['address_line_2'] === null) {
            $object->setAddressLine2(null);
        }
        if (\array_key_exists('address_city', $data) && $data['address_city'] !== null) {
            $object->setAddressCity($data['address_city']);
        } elseif (\array_key_exists('address_city', $data) && $data['address_city'] === null) {
            $object->setAddressCity(null);
        }
        if (\array_key_exists('address_postal_code', $data) && $data['address_postal_code'] !== null) {
            $object->setAddressPostalCode($data['address_postal_code']);
        } elseif (\array_key_exists('address_postal_code', $data) && $data['address_postal_code'] === null) {
            $object->setAddressPostalCode(null);
        }
        if (\array_key_exists('address_country', $data) && $data['address_country'] !== null) {
            $object->setAddressCountry($data['address_country']);
        } elseif (\array_key_exists('address_country', $data) && $data['address_country'] === null) {
            $object->setAddressCountry(null);
        }

        return $object;
    }

    /**
     * @return array|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        if (null !== $object->getId()) {
            $data['id'] = $object->getId();
        }
        if (null !== $object->getFirstName()) {
            $data['first_name'] = $object->getFirstName();
        }
        if (null !== $object->getLastName()) {
            $data['last_name'] = $object->getLastName();
        }
        if (null !== $object->getEmail()) {
            $data['email'] = $object->getEmail();
        }
        if (null !== $object->getLocale()) {
            $data['locale'] = $object->getLocale();
        }
        if (null !== $object->getPhoneNumber()) {
            $data['phone_number'] = $object->getPhoneNumber();
        }
        if (null !== $object->getCompanyName()) {
            $data['company_name'] = $object->getCompanyName();
        }
        if (null !== $object->getJobTitle()) {
            $data['job_title'] = $object->getJobTitle();
        }
        if (null !== $object->getAddressLine1()) {
            $data['address_line_1'] = $object->getAddressLine1();
        }
        if (null !== $object->getAddressLine2()) {
            $data['address_line_2'] = $object->getAddressLine2();
        }
        if (null !== $object->getAddressCity()) {
            $data['address_city'] = $object->getAddressCity();
        }
        if (null !== $object->getAddressPostalCode()) {
            $data['address_postal_code'] = $object->getAddressPostalCode();
        }
        if (null !== $object->getAddressCountry()) {
            $data['address_country'] = $object->getAddressCountry();
        }

        return $data;
    }
}
