<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Normalizer;

use IIYousign\Runtime\Normalizer\CheckArray;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class SignatureRequestActivatedNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;

    public function supportsDenormalization($data, $type, $format = null): bool
    {
        return $type === 'IIYousign\\Model\\SignatureRequestActivated';
    }

    public function supportsNormalization($data, $format = null): bool
    {
        return is_object($data) && get_class($data) === 'IIYousign\\Model\\SignatureRequestActivated';
    }

    /**
     * @return mixed
     */
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \IIYousign\Model\SignatureRequestActivated();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('id', $data)) {
            $object->setId($data['id']);
        }
        if (\array_key_exists('status', $data)) {
            $object->setStatus($data['status']);
        }
        if (\array_key_exists('name', $data)) {
            $object->setName($data['name']);
        }
        if (\array_key_exists('delivery_mode', $data)) {
            $object->setDeliveryMode($data['delivery_mode']);
        }
        if (\array_key_exists('created_at', $data)) {
            $object->setCreatedAt(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['created_at']));
        }
        if (\array_key_exists('ordered_signers', $data)) {
            $object->setOrderedSigners($data['ordered_signers']);
        }
        if (\array_key_exists('reminder_settings', $data) && $data['reminder_settings'] !== null) {
            $object->setReminderSettings($this->denormalizer->denormalize($data['reminder_settings'], 'IIYousign\\Model\\SignatureRequestActivatedReminderSettings', 'json', $context));
        } elseif (\array_key_exists('reminder_settings', $data) && $data['reminder_settings'] === null) {
            $object->setReminderSettings(null);
        }
        if (\array_key_exists('timezone', $data)) {
            $object->setTimezone($data['timezone']);
        }
        if (\array_key_exists('email_custom_note', $data) && $data['email_custom_note'] !== null) {
            $object->setEmailCustomNote($data['email_custom_note']);
        } elseif (\array_key_exists('email_custom_note', $data) && $data['email_custom_note'] === null) {
            $object->setEmailCustomNote(null);
        }
        if (\array_key_exists('expiration_date', $data)) {
            $object->setExpirationDate(\DateTime::createFromFormat('Y-m-d\\TH:i:sP', $data['expiration_date']));
        }
        if (\array_key_exists('signers', $data)) {
            $values = [];
            foreach ($data['signers'] as $value) {
                $values[] = $this->denormalizer->denormalize($value, 'IIYousign\\Model\\SignatureRequestActivatedSignersItem', 'json', $context);
            }
            $object->setSigners($values);
        }
        if (\array_key_exists('documents', $data)) {
            $values_1 = [];
            foreach ($data['documents'] as $value_1) {
                $values_1[] = $this->denormalizer->denormalize($value_1, 'IIYousign\\Model\\SignatureRequestActivatedDocumentsItem', 'json', $context);
            }
            $object->setDocuments($values_1);
        }
        if (\array_key_exists('external_id', $data) && $data['external_id'] !== null) {
            $object->setExternalId($data['external_id']);
        } elseif (\array_key_exists('external_id', $data) && $data['external_id'] === null) {
            $object->setExternalId(null);
        }
        if (\array_key_exists('branding_id', $data) && $data['branding_id'] !== null) {
            $object->setBrandingId($data['branding_id']);
        } elseif (\array_key_exists('branding_id', $data) && $data['branding_id'] === null) {
            $object->setBrandingId(null);
        }

        return $object;
    }

    /**
     * @return array|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        if (null !== $object->getId()) {
            $data['id'] = $object->getId();
        }
        if (null !== $object->getStatus()) {
            $data['status'] = $object->getStatus();
        }
        if (null !== $object->getName()) {
            $data['name'] = $object->getName();
        }
        if (null !== $object->getDeliveryMode()) {
            $data['delivery_mode'] = $object->getDeliveryMode();
        }
        if (null !== $object->getCreatedAt()) {
            $data['created_at'] = $object->getCreatedAt()->format('Y-m-d\\TH:i:sP');
        }
        if (null !== $object->getOrderedSigners()) {
            $data['ordered_signers'] = $object->getOrderedSigners();
        }
        if (null !== $object->getReminderSettings()) {
            $data['reminder_settings'] = $this->normalizer->normalize($object->getReminderSettings(), 'json', $context);
        }
        if (null !== $object->getTimezone()) {
            $data['timezone'] = $object->getTimezone();
        }
        if (null !== $object->getEmailCustomNote()) {
            $data['email_custom_note'] = $object->getEmailCustomNote();
        }
        if (null !== $object->getExpirationDate()) {
            $data['expiration_date'] = $object->getExpirationDate()->format('Y-m-d\\TH:i:sP');
        }
        if (null !== $object->getSigners()) {
            $values = [];
            foreach ($object->getSigners() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $data['signers'] = $values;
        }
        if (null !== $object->getDocuments()) {
            $values_1 = [];
            foreach ($object->getDocuments() as $value_1) {
                $values_1[] = $this->normalizer->normalize($value_1, 'json', $context);
            }
            $data['documents'] = $values_1;
        }
        if (null !== $object->getExternalId()) {
            $data['external_id'] = $object->getExternalId();
        }
        if (null !== $object->getBrandingId()) {
            $data['branding_id'] = $object->getBrandingId();
        }

        return $data;
    }
}
