<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Normalizer;

use IIYousign\Runtime\Normalizer\CheckArray;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class SignatureRequestsSignatureRequestIdPatchBodyNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;

    public function supportsDenormalization($data, $type, $format = null): bool
    {
        return $type === 'IIYousign\\Model\\SignatureRequestsSignatureRequestIdPatchBody';
    }

    public function supportsNormalization($data, $format = null): bool
    {
        return is_object($data) && get_class($data) === 'IIYousign\\Model\\SignatureRequestsSignatureRequestIdPatchBody';
    }

    /**
     * @return mixed
     */
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \IIYousign\Model\SignatureRequestsSignatureRequestIdPatchBody();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('name', $data)) {
            $object->setName($data['name']);
        }
        if (\array_key_exists('delivery_mode', $data)) {
            $object->setDeliveryMode($data['delivery_mode']);
        }
        if (\array_key_exists('ordered_signers', $data)) {
            $object->setOrderedSigners($data['ordered_signers']);
        }
        if (\array_key_exists('reminder_settings', $data) && $data['reminder_settings'] !== null) {
            $object->setReminderSettings($this->denormalizer->denormalize($data['reminder_settings'], 'IIYousign\\Model\\SignatureRequestsSignatureRequestIdPatchBodyReminderSettings', 'json', $context));
        } elseif (\array_key_exists('reminder_settings', $data) && $data['reminder_settings'] === null) {
            $object->setReminderSettings(null);
        }
        if (\array_key_exists('timezone', $data)) {
            $object->setTimezone($data['timezone']);
        }
        if (\array_key_exists('email_custom_note', $data) && $data['email_custom_note'] !== null) {
            $object->setEmailCustomNote($data['email_custom_note']);
        } elseif (\array_key_exists('email_custom_note', $data) && $data['email_custom_note'] === null) {
            $object->setEmailCustomNote(null);
        }
        if (\array_key_exists('expiration_date', $data)) {
            $object->setExpirationDate(\DateTime::createFromFormat('Y-m-d', $data['expiration_date'])->setTime(0, 0, 0));
        }
        if (\array_key_exists('external_id', $data) && $data['external_id'] !== null) {
            $object->setExternalId($data['external_id']);
        } elseif (\array_key_exists('external_id', $data) && $data['external_id'] === null) {
            $object->setExternalId(null);
        }
        if (\array_key_exists('branding_id', $data) && $data['branding_id'] !== null) {
            $object->setBrandingId($data['branding_id']);
        } elseif (\array_key_exists('branding_id', $data) && $data['branding_id'] === null) {
            $object->setBrandingId(null);
        }

        return $object;
    }

    /**
     * @return array|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        if (null !== $object->getName()) {
            $data['name'] = $object->getName();
        }
        if (null !== $object->getDeliveryMode()) {
            $data['delivery_mode'] = $object->getDeliveryMode();
        }
        if (null !== $object->getOrderedSigners()) {
            $data['ordered_signers'] = $object->getOrderedSigners();
        }
        if (null !== $object->getReminderSettings()) {
            $data['reminder_settings'] = $this->normalizer->normalize($object->getReminderSettings(), 'json', $context);
        }
        if (null !== $object->getTimezone()) {
            $data['timezone'] = $object->getTimezone();
        }
        if (null !== $object->getEmailCustomNote()) {
            $data['email_custom_note'] = $object->getEmailCustomNote();
        }
        if (null !== $object->getExpirationDate()) {
            $data['expiration_date'] = $object->getExpirationDate()->format('Y-m-d');
        }
        if (null !== $object->getExternalId()) {
            $data['external_id'] = $object->getExternalId();
        }
        if (null !== $object->getBrandingId()) {
            $data['branding_id'] = $object->getBrandingId();
        }

        return $data;
    }
}
