<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Normalizer;

use IIYousign\Runtime\Normalizer\CheckArray;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class SignerNormalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;

    public function supportsDenormalization($data, $type, $format = null): bool
    {
        return $type === 'IIYousign\\Model\\Signer';
    }

    public function supportsNormalization($data, $format = null): bool
    {
        return is_object($data) && get_class($data) === 'IIYousign\\Model\\Signer';
    }

    /**
     * @return mixed
     */
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \IIYousign\Model\Signer();
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('id', $data)) {
            $object->setId($data['id']);
        }
        if (\array_key_exists('info', $data)) {
            $object->setInfo($this->denormalizer->denormalize($data['info'], 'IIYousign\\Model\\SignerInfo', 'json', $context));
        }
        if (\array_key_exists('status', $data) && $data['status'] !== null) {
            $object->setStatus($data['status']);
        } elseif (\array_key_exists('status', $data) && $data['status'] === null) {
            $object->setStatus(null);
        }
        if (\array_key_exists('fields', $data) && $data['fields'] !== null) {
            $values = [];
            foreach ($data['fields'] as $value) {
                $values[] = $value;
            }
            $object->setFields($values);
        } elseif (\array_key_exists('fields', $data) && $data['fields'] === null) {
            $object->setFields(null);
        }
        if (\array_key_exists('signature_level', $data) && $data['signature_level'] !== null) {
            $object->setSignatureLevel($data['signature_level']);
        } elseif (\array_key_exists('signature_level', $data) && $data['signature_level'] === null) {
            $object->setSignatureLevel(null);
        }
        if (\array_key_exists('signature_authentication_mode', $data) && $data['signature_authentication_mode'] !== null) {
            $object->setSignatureAuthenticationMode($data['signature_authentication_mode']);
        } elseif (\array_key_exists('signature_authentication_mode', $data) && $data['signature_authentication_mode'] === null) {
            $object->setSignatureAuthenticationMode(null);
        }
        if (\array_key_exists('signature_link', $data) && $data['signature_link'] !== null) {
            $object->setSignatureLink($data['signature_link']);
        } elseif (\array_key_exists('signature_link', $data) && $data['signature_link'] === null) {
            $object->setSignatureLink(null);
        }
        if (\array_key_exists('signature_image_preview', $data) && $data['signature_image_preview'] !== null) {
            $object->setSignatureImagePreview($data['signature_image_preview']);
        } elseif (\array_key_exists('signature_image_preview', $data) && $data['signature_image_preview'] === null) {
            $object->setSignatureImagePreview(null);
        }
        if (\array_key_exists('redirect_urls', $data)) {
            $object->setRedirectUrls($this->denormalizer->denormalize($data['redirect_urls'], 'IIYousign\\Model\\SignerRedirectUrls', 'json', $context));
        }
        if (\array_key_exists('custom_text', $data) && $data['custom_text'] !== null) {
            $object->setCustomText($this->denormalizer->denormalize($data['custom_text'], 'IIYousign\\Model\\SignerCustomText', 'json', $context));
        } elseif (\array_key_exists('custom_text', $data) && $data['custom_text'] === null) {
            $object->setCustomText(null);
        }

        return $object;
    }

    /**
     * @return array|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        if (null !== $object->getId()) {
            $data['id'] = $object->getId();
        }
        if (null !== $object->getInfo()) {
            $data['info'] = $this->normalizer->normalize($object->getInfo(), 'json', $context);
        }
        if (null !== $object->getStatus()) {
            $data['status'] = $object->getStatus();
        }
        if (null !== $object->getFields()) {
            $values = [];
            foreach ($object->getFields() as $value) {
                $values[] = $this->normalizer->normalize($value, 'json', $context);
            }
            $data['fields'] = $values;
        }
        if (null !== $object->getSignatureLevel()) {
            $data['signature_level'] = $object->getSignatureLevel();
        }
        if (null !== $object->getSignatureAuthenticationMode()) {
            $data['signature_authentication_mode'] = $object->getSignatureAuthenticationMode();
        }
        if (null !== $object->getSignatureLink()) {
            $data['signature_link'] = $object->getSignatureLink();
        }
        if (null !== $object->getSignatureImagePreview()) {
            $data['signature_image_preview'] = $object->getSignatureImagePreview();
        }
        if (null !== $object->getRedirectUrls()) {
            $data['redirect_urls'] = $this->normalizer->normalize($object->getRedirectUrls(), 'json', $context);
        }
        if (null !== $object->getCustomText()) {
            $data['custom_text'] = $this->normalizer->normalize($object->getCustomText(), 'json', $context);
        }

        return $data;
    }
}
