<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Normalizer;

use IIYousign\Runtime\Normalizer\CheckArray;
use Jane\Component\JsonSchemaRuntime\Reference;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\DenormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\DenormalizerInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareInterface;
use Symfony\Component\Serializer\Normalizer\NormalizerAwareTrait;
use Symfony\Component\Serializer\Normalizer\NormalizerInterface;

class SignatureRequestsSignatureRequestIdSignersSignerIdAuditTrailsGetResponse200Normalizer implements DenormalizerInterface, NormalizerInterface, DenormalizerAwareInterface, NormalizerAwareInterface
{
    use DenormalizerAwareTrait;
    use NormalizerAwareTrait;
    use CheckArray;

    public function supportsDenormalization($data, $type, $format = null): bool
    {
        return $type === 'IIYousign\\Model\\SignatureRequestsSignatureRequestIdSignersSignerIdAuditTrailsGetResponse200';
    }

    public function supportsNormalization($data, $format = null): bool
    {
        return is_object($data) && get_class($data) === 'IIYousign\\Model\\SignatureRequestsSignatureRequestIdSignersSignerIdAuditTrailsGetResponse200';
    }

    /**
     * @return mixed
     */
    public function denormalize($data, $class, $format = null, array $context = [])
    {
        if (isset($data['$ref'])) {
            return new Reference($data['$ref'], $context['document-origin']);
        }
        if (isset($data['$recursiveRef'])) {
            return new Reference($data['$recursiveRef'], $context['document-origin']);
        }
        $object = new \IIYousign\Model\SignatureRequestsSignatureRequestIdSignersSignerIdAuditTrailsGetResponse200();
        if (\array_key_exists('version', $data) && \is_int($data['version'])) {
            $data['version'] = (float) $data['version'];
        }
        if (null === $data || false === \is_array($data)) {
            return $object;
        }
        if (\array_key_exists('version', $data)) {
            $object->setVersion($data['version']);
        }
        if (\array_key_exists('signature_request', $data)) {
            $object->setSignatureRequest($data['signature_request']);
        }
        if (\array_key_exists('sender', $data)) {
            $object->setSender($data['sender']);
        }
        if (\array_key_exists('signer', $data)) {
            $object->setSigner($data['signer']);
        }
        if (\array_key_exists('documents', $data)) {
            $values = [];
            foreach ($data['documents'] as $value) {
                $values[] = $value;
            }
            $object->setDocuments($values);
        }
        if (\array_key_exists('organization', $data)) {
            $object->setOrganization($data['organization']);
        }
        if (\array_key_exists('authentication', $data)) {
            $object->setAuthentication($data['authentication']);
        }
        if (\array_key_exists('electronic_signature_level', $data)) {
            $object->setElectronicSignatureLevel($data['electronic_signature_level']);
        }

        return $object;
    }

    /**
     * @return array|string|int|float|bool|\ArrayObject|null
     */
    public function normalize($object, $format = null, array $context = [])
    {
        $data = [];
        if (null !== $object->getVersion()) {
            $data['version'] = $object->getVersion();
        }
        if (null !== $object->getSignatureRequest()) {
            $data['signature_request'] = $object->getSignatureRequest();
        }
        if (null !== $object->getSender()) {
            $data['sender'] = $object->getSender();
        }
        if (null !== $object->getSigner()) {
            $data['signer'] = $object->getSigner();
        }
        if (null !== $object->getDocuments()) {
            $values = [];
            foreach ($object->getDocuments() as $value) {
                $values[] = $value;
            }
            $data['documents'] = $values;
        }
        if (null !== $object->getOrganization()) {
            $data['organization'] = $object->getOrganization();
        }
        if (null !== $object->getAuthentication()) {
            $data['authentication'] = $object->getAuthentication();
        }
        if (null !== $object->getElectronicSignatureLevel()) {
            $data['electronic_signature_level'] = $object->getElectronicSignatureLevel();
        }

        return $data;
    }
}
