<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class ConsumptionsGetResponse200
{
    /**
     * @var ConsumptionsGetResponse200App
     */
    protected $app;
    /**
     * @var ConsumptionsGetResponse200Api
     */
    protected $api;
    /**
     * @var ConsumptionsGetResponse200Connector
     */
    protected $connector;

    public function getApp(): ConsumptionsGetResponse200App
    {
        return $this->app;
    }

    public function setApp(ConsumptionsGetResponse200App $app): self
    {
        $this->app = $app;

        return $this;
    }

    public function getApi(): ConsumptionsGetResponse200Api
    {
        return $this->api;
    }

    public function setApi(ConsumptionsGetResponse200Api $api): self
    {
        $this->api = $api;

        return $this;
    }

    public function getConnector(): ConsumptionsGetResponse200Connector
    {
        return $this->connector;
    }

    public function setConnector(ConsumptionsGetResponse200Connector $connector): self
    {
        $this->connector = $connector;

        return $this;
    }
}
