<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class ConsumptionsGetResponse200App
{
    /**
     * @var int
     */
    protected $electronicSignature;
    /**
     * @var int
     */
    protected $advancedElectronicSignature;
    /**
     * @var int
     */
    protected $advancedElectronicSignatureWithQualifiedCertificate;

    public function getElectronicSignature(): int
    {
        return $this->electronicSignature;
    }

    public function setElectronicSignature(int $electronicSignature): self
    {
        $this->electronicSignature = $electronicSignature;

        return $this;
    }

    public function getAdvancedElectronicSignature(): int
    {
        return $this->advancedElectronicSignature;
    }

    public function setAdvancedElectronicSignature(int $advancedElectronicSignature): self
    {
        $this->advancedElectronicSignature = $advancedElectronicSignature;

        return $this;
    }

    public function getAdvancedElectronicSignatureWithQualifiedCertificate(): int
    {
        return $this->advancedElectronicSignatureWithQualifiedCertificate;
    }

    public function setAdvancedElectronicSignatureWithQualifiedCertificate(int $advancedElectronicSignatureWithQualifiedCertificate): self
    {
        $this->advancedElectronicSignatureWithQualifiedCertificate = $advancedElectronicSignatureWithQualifiedCertificate;

        return $this;
    }
}
