<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class ContactsGetResponse200
{
    /**
     * Cursor based pagination.
     *
     * @var Pagination
     */
    protected $meta;
    /**
     * @var Contact[]
     */
    protected $data;

    /**
     * Cursor based pagination.
     */
    public function getMeta(): Pagination
    {
        return $this->meta;
    }

    /**
     * Cursor based pagination.
     */
    public function setMeta(Pagination $meta): self
    {
        $this->meta = $meta;

        return $this;
    }

    /**
     * @return Contact[]
     */
    public function getData(): array
    {
        return $this->data;
    }

    /**
     * @param Contact[] $data
     */
    public function setData(array $data): self
    {
        $this->data = $data;

        return $this;
    }
}
