<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class Document
{
    /**
     * @var string
     */
    protected $id;
    /**
     * @var string
     */
    protected $filename;
    /**
     * @var string
     */
    protected $nature;
    /**
     * @var string
     */
    protected $contentType;
    /**
     * Sha256 checksum.
     *
     * @var string
     */
    protected $sha256;
    /**
     * @var bool
     */
    protected $isProtected;
    /**
     * @var bool
     */
    protected $isSigned;
    /**
     * @var \DateTime
     */
    protected $createdAt;
    /**
     * Number of pages for signable document.
     *
     * @var int|null
     */
    protected $totalPages;
    /**
     * If protected by password and not yet unlocked.
     *
     * @var bool
     */
    protected $isLocked;
    /**
     * @var DocumentInitials|null
     */
    protected $initials;
    /**
     * Number of parsed anchors from the document.
     *
     * @var int
     */
    protected $totalAnchors;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getFilename(): string
    {
        return $this->filename;
    }

    public function setFilename(string $filename): self
    {
        $this->filename = $filename;

        return $this;
    }

    public function getNature(): string
    {
        return $this->nature;
    }

    public function setNature(string $nature): self
    {
        $this->nature = $nature;

        return $this;
    }

    public function getContentType(): string
    {
        return $this->contentType;
    }

    public function setContentType(string $contentType): self
    {
        $this->contentType = $contentType;

        return $this;
    }

    /**
     * Sha256 checksum.
     */
    public function getSha256(): string
    {
        return $this->sha256;
    }

    /**
     * Sha256 checksum.
     */
    public function setSha256(string $sha256): self
    {
        $this->sha256 = $sha256;

        return $this;
    }

    public function getIsProtected(): bool
    {
        return $this->isProtected;
    }

    public function setIsProtected(bool $isProtected): self
    {
        $this->isProtected = $isProtected;

        return $this;
    }

    public function getIsSigned(): bool
    {
        return $this->isSigned;
    }

    public function setIsSigned(bool $isSigned): self
    {
        $this->isSigned = $isSigned;

        return $this;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Number of pages for signable document.
     */
    public function getTotalPages(): ?int
    {
        return $this->totalPages;
    }

    /**
     * Number of pages for signable document.
     */
    public function setTotalPages(?int $totalPages): self
    {
        $this->totalPages = $totalPages;

        return $this;
    }

    /**
     * If protected by password and not yet unlocked.
     */
    public function getIsLocked(): bool
    {
        return $this->isLocked;
    }

    /**
     * If protected by password and not yet unlocked.
     */
    public function setIsLocked(bool $isLocked): self
    {
        $this->isLocked = $isLocked;

        return $this;
    }

    public function getInitials(): ?DocumentInitials
    {
        return $this->initials;
    }

    public function setInitials(?DocumentInitials $initials): self
    {
        $this->initials = $initials;

        return $this;
    }

    /**
     * Number of parsed anchors from the document.
     */
    public function getTotalAnchors(): int
    {
        return $this->totalAnchors;
    }

    /**
     * Number of parsed anchors from the document.
     */
    public function setTotalAnchors(int $totalAnchors): self
    {
        $this->totalAnchors = $totalAnchors;

        return $this;
    }
}
