<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class ResponseBadRequestError
{
    /**
     * @var string
     */
    protected $type;
    /**
     * @var string
     */
    protected $detail;
    /**
     * @var ResponseBadRequestErrorInvalidParamsItem[]
     */
    protected $invalidParams;

    public function getType(): string
    {
        return $this->type;
    }

    public function setType(string $type): self
    {
        $this->type = $type;

        return $this;
    }

    public function getDetail(): string
    {
        return $this->detail;
    }

    public function setDetail(string $detail): self
    {
        $this->detail = $detail;

        return $this;
    }

    /**
     * @return ResponseBadRequestErrorInvalidParamsItem[]
     */
    public function getInvalidParams(): array
    {
        return $this->invalidParams;
    }

    /**
     * @param ResponseBadRequestErrorInvalidParamsItem[] $invalidParams
     */
    public function setInvalidParams(array $invalidParams): self
    {
        $this->invalidParams = $invalidParams;

        return $this;
    }
}
