<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class SignatureRequestActivated
{
    /**
     * @var string
     */
    protected $id;
    /**
     * @var string
     */
    protected $status;
    /**
     * @var string
     */
    protected $name;
    /**
     * @var string
     */
    protected $deliveryMode;
    /**
     * @var \DateTime
     */
    protected $createdAt;
    /**
     * Enable an ordered workflow, each signer will be requested to sign in a sequential order.
     *
     * @var bool
     */
    protected $orderedSigners;
    /**
     * @var SignatureRequestActivatedReminderSettings|null
     */
    protected $reminderSettings;
    /**
     * @var string
     */
    protected $timezone;
    /**
     * @var string|null
     */
    protected $emailCustomNote;
    /**
     * @var \DateTime
     */
    protected $expirationDate;
    /**
     * @var SignatureRequestActivatedSignersItem[]
     */
    protected $signers;
    /**
     * @var SignatureRequestActivatedDocumentsItem[]
     */
    protected $documents;
    /**
     * @var string|null
     */
    protected $externalId;
    /**
     * @var string|null
     */
    protected $brandingId;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getStatus(): string
    {
        return $this->status;
    }

    public function setStatus(string $status): self
    {
        $this->status = $status;

        return $this;
    }

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    public function getDeliveryMode(): string
    {
        return $this->deliveryMode;
    }

    public function setDeliveryMode(string $deliveryMode): self
    {
        $this->deliveryMode = $deliveryMode;

        return $this;
    }

    public function getCreatedAt(): \DateTime
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTime $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    /**
     * Enable an ordered workflow, each signer will be requested to sign in a sequential order.
     */
    public function getOrderedSigners(): bool
    {
        return $this->orderedSigners;
    }

    /**
     * Enable an ordered workflow, each signer will be requested to sign in a sequential order.
     */
    public function setOrderedSigners(bool $orderedSigners): self
    {
        $this->orderedSigners = $orderedSigners;

        return $this;
    }

    public function getReminderSettings(): ?SignatureRequestActivatedReminderSettings
    {
        return $this->reminderSettings;
    }

    public function setReminderSettings(?SignatureRequestActivatedReminderSettings $reminderSettings): self
    {
        $this->reminderSettings = $reminderSettings;

        return $this;
    }

    public function getTimezone(): string
    {
        return $this->timezone;
    }

    public function setTimezone(string $timezone): self
    {
        $this->timezone = $timezone;

        return $this;
    }

    public function getEmailCustomNote(): ?string
    {
        return $this->emailCustomNote;
    }

    public function setEmailCustomNote(?string $emailCustomNote): self
    {
        $this->emailCustomNote = $emailCustomNote;

        return $this;
    }

    public function getExpirationDate(): \DateTime
    {
        return $this->expirationDate;
    }

    public function setExpirationDate(\DateTime $expirationDate): self
    {
        $this->expirationDate = $expirationDate;

        return $this;
    }

    /**
     * @return SignatureRequestActivatedSignersItem[]
     */
    public function getSigners(): array
    {
        return $this->signers;
    }

    /**
     * @param SignatureRequestActivatedSignersItem[] $signers
     */
    public function setSigners(array $signers): self
    {
        $this->signers = $signers;

        return $this;
    }

    /**
     * @return SignatureRequestActivatedDocumentsItem[]
     */
    public function getDocuments(): array
    {
        return $this->documents;
    }

    /**
     * @param SignatureRequestActivatedDocumentsItem[] $documents
     */
    public function setDocuments(array $documents): self
    {
        $this->documents = $documents;

        return $this;
    }

    public function getExternalId(): ?string
    {
        return $this->externalId;
    }

    public function setExternalId(?string $externalId): self
    {
        $this->externalId = $externalId;

        return $this;
    }

    public function getBrandingId(): ?string
    {
        return $this->brandingId;
    }

    public function setBrandingId(?string $brandingId): self
    {
        $this->brandingId = $brandingId;

        return $this;
    }
}
