<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class SignatureRequestsSignatureRequestIdDocumentsDocumentIdPatchBody
{
    /**
     * @var string
     */
    protected $nature;
    /**
     * Insert just after the position of the specified document id.
     *
     * @var string|null
     */
    protected $insertAfterId;
    /**
     * To unk document.
     *
     * @var string
     */
    protected $password;
    /**
     * @var mixed|null
     */
    protected $initials;

    public function getNature(): string
    {
        return $this->nature;
    }

    public function setNature(string $nature): self
    {
        $this->nature = $nature;

        return $this;
    }

    /**
     * Insert just after the position of the specified document id.
     */
    public function getInsertAfterId(): ?string
    {
        return $this->insertAfterId;
    }

    /**
     * Insert just after the position of the specified document id.
     */
    public function setInsertAfterId(?string $insertAfterId): self
    {
        $this->insertAfterId = $insertAfterId;

        return $this;
    }

    /**
     * To unk document.
     */
    public function getPassword(): string
    {
        return $this->password;
    }

    /**
     * To unk document.
     */
    public function setPassword(string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getInitials()
    {
        return $this->initials;
    }

    /**
     * @param mixed $initials
     */
    public function setInitials($initials): self
    {
        $this->initials = $initials;

        return $this;
    }
}
