<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class SignatureRequestsSignatureRequestIdSignersSignerIdPatchBody
{
    /**
     * @var SignatureRequestsSignatureRequestIdSignersSignerIdPatchBodyInfo
     */
    protected $info;
    /**
     * @var string|null
     */
    protected $insertAfterId;
    /**
     * @var string
     */
    protected $signatureLevel = 'electronic_signature';
    /**
     * @var string|null
     */
    protected $signatureAuthenticationMode = 'no_otp';
    /**
     * @var SignatureRequestsSignatureRequestIdSignersSignerIdPatchBodyRedirectUrls
     */
    protected $redirectUrls;
    /**
     * @var SignatureRequestsSignatureRequestIdSignersSignerIdPatchBodyCustomText|null
     */
    protected $customText;

    public function getInfo(): SignatureRequestsSignatureRequestIdSignersSignerIdPatchBodyInfo
    {
        return $this->info;
    }

    public function setInfo(SignatureRequestsSignatureRequestIdSignersSignerIdPatchBodyInfo $info): self
    {
        $this->info = $info;

        return $this;
    }

    public function getInsertAfterId(): ?string
    {
        return $this->insertAfterId;
    }

    public function setInsertAfterId(?string $insertAfterId): self
    {
        $this->insertAfterId = $insertAfterId;

        return $this;
    }

    public function getSignatureLevel(): string
    {
        return $this->signatureLevel;
    }

    public function setSignatureLevel(string $signatureLevel): self
    {
        $this->signatureLevel = $signatureLevel;

        return $this;
    }

    public function getSignatureAuthenticationMode(): ?string
    {
        return $this->signatureAuthenticationMode;
    }

    public function setSignatureAuthenticationMode(?string $signatureAuthenticationMode): self
    {
        $this->signatureAuthenticationMode = $signatureAuthenticationMode;

        return $this;
    }

    public function getRedirectUrls(): SignatureRequestsSignatureRequestIdSignersSignerIdPatchBodyRedirectUrls
    {
        return $this->redirectUrls;
    }

    public function setRedirectUrls(SignatureRequestsSignatureRequestIdSignersSignerIdPatchBodyRedirectUrls $redirectUrls): self
    {
        $this->redirectUrls = $redirectUrls;

        return $this;
    }

    public function getCustomText(): ?SignatureRequestsSignatureRequestIdSignersSignerIdPatchBodyCustomText
    {
        return $this->customText;
    }

    public function setCustomText(?SignatureRequestsSignatureRequestIdSignersSignerIdPatchBodyCustomText $customText): self
    {
        $this->customText = $customText;

        return $this;
    }
}
