<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class SignatureRequestSignerFromInfoInput
{
    /**
     * create new signer.
     *
     * @var SignatureRequestSignerFromInfoInputInfo
     */
    protected $info;
    /**
     * @var mixed[]|null
     */
    protected $fields;
    /**
     * @var string
     */
    protected $signatureLevel = 'electronic_signature';
    /**
     * @var string|null
     */
    protected $signatureAuthenticationMode = 'no_otp';
    /**
     * @var SignatureRequestSignerFromInfoInputRedirectUrls|null
     */
    protected $redirectUrls;

    /**
     * create new signer.
     */
    public function getInfo(): SignatureRequestSignerFromInfoInputInfo
    {
        return $this->info;
    }

    /**
     * create new signer.
     */
    public function setInfo(SignatureRequestSignerFromInfoInputInfo $info): self
    {
        $this->info = $info;

        return $this;
    }

    /**
     * @return mixed[]|null
     */
    public function getFields(): ?array
    {
        return $this->fields;
    }

    /**
     * @param mixed[]|null $fields
     */
    public function setFields(?array $fields): self
    {
        $this->fields = $fields;

        return $this;
    }

    public function getSignatureLevel(): string
    {
        return $this->signatureLevel;
    }

    public function setSignatureLevel(string $signatureLevel): self
    {
        $this->signatureLevel = $signatureLevel;

        return $this;
    }

    public function getSignatureAuthenticationMode(): ?string
    {
        return $this->signatureAuthenticationMode;
    }

    public function setSignatureAuthenticationMode(?string $signatureAuthenticationMode): self
    {
        $this->signatureAuthenticationMode = $signatureAuthenticationMode;

        return $this;
    }

    public function getRedirectUrls(): ?SignatureRequestSignerFromInfoInputRedirectUrls
    {
        return $this->redirectUrls;
    }

    public function setRedirectUrls(?SignatureRequestSignerFromInfoInputRedirectUrls $redirectUrls): self
    {
        $this->redirectUrls = $redirectUrls;

        return $this;
    }
}
