<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class Signer
{
    /**
     * @var string
     */
    protected $id;
    /**
     * @var SignerInfo
     */
    protected $info;
    /**
     * @var string|null
     */
    protected $status = 'initiated';
    /**
     * @var mixed[]|null
     */
    protected $fields;
    /**
     * @var string|null
     */
    protected $signatureLevel = 'electronic_signature';
    /**
     * @var string|null
     */
    protected $signatureAuthenticationMode = 'no_otp';
    /**
     * @deprecated
     *
     * @var string|null
     */
    protected $signatureLink;
    /**
     * @var string|null
     */
    protected $signatureImagePreview;
    /**
     * @var SignerRedirectUrls
     */
    protected $redirectUrls;
    /**
     * @var SignerCustomText|null
     */
    protected $customText;

    public function getId(): string
    {
        return $this->id;
    }

    public function setId(string $id): self
    {
        $this->id = $id;

        return $this;
    }

    public function getInfo(): SignerInfo
    {
        return $this->info;
    }

    public function setInfo(SignerInfo $info): self
    {
        $this->info = $info;

        return $this;
    }

    public function getStatus(): ?string
    {
        return $this->status;
    }

    public function setStatus(?string $status): self
    {
        $this->status = $status;

        return $this;
    }

    /**
     * @return mixed[]|null
     */
    public function getFields(): ?array
    {
        return $this->fields;
    }

    /**
     * @param mixed[]|null $fields
     */
    public function setFields(?array $fields): self
    {
        $this->fields = $fields;

        return $this;
    }

    public function getSignatureLevel(): ?string
    {
        return $this->signatureLevel;
    }

    public function setSignatureLevel(?string $signatureLevel): self
    {
        $this->signatureLevel = $signatureLevel;

        return $this;
    }

    public function getSignatureAuthenticationMode(): ?string
    {
        return $this->signatureAuthenticationMode;
    }

    public function setSignatureAuthenticationMode(?string $signatureAuthenticationMode): self
    {
        $this->signatureAuthenticationMode = $signatureAuthenticationMode;

        return $this;
    }

    /**
     * @deprecated
     */
    public function getSignatureLink(): ?string
    {
        return $this->signatureLink;
    }

    /**
     * @deprecated
     */
    public function setSignatureLink(?string $signatureLink): self
    {
        $this->signatureLink = $signatureLink;

        return $this;
    }

    public function getSignatureImagePreview(): ?string
    {
        return $this->signatureImagePreview;
    }

    public function setSignatureImagePreview(?string $signatureImagePreview): self
    {
        $this->signatureImagePreview = $signatureImagePreview;

        return $this;
    }

    public function getRedirectUrls(): SignerRedirectUrls
    {
        return $this->redirectUrls;
    }

    public function setRedirectUrls(SignerRedirectUrls $redirectUrls): self
    {
        $this->redirectUrls = $redirectUrls;

        return $this;
    }

    public function getCustomText(): ?SignerCustomText
    {
        return $this->customText;
    }

    public function setCustomText(?SignerCustomText $customText): self
    {
        $this->customText = $customText;

        return $this;
    }
}
