<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class SignatureRequestsSignatureRequestIdPatchBody
{
    /**
     * @var string
     */
    protected $name;
    /**
     * Delivery mode to notify signers.
     *
     * @var string
     */
    protected $deliveryMode;
    /**
     * Enable an ordered workflow, each signer will be requested to sign in a sequential order.
     *
     * @var bool
     */
    protected $orderedSigners;
    /**
     * @var SignatureRequestsSignatureRequestIdPatchBodyReminderSettings|null
     */
    protected $reminderSettings;
    /**
     * tz database format.
     *
     * @var string
     */
    protected $timezone;
    /**
     * @var string|null
     */
    protected $emailCustomNote;
    /**
     * @var \DateTime
     */
    protected $expirationDate;
    /**
     * @var string|null
     */
    protected $externalId;
    /**
     * @var string|null
     */
    protected $brandingId;

    public function getName(): string
    {
        return $this->name;
    }

    public function setName(string $name): self
    {
        $this->name = $name;

        return $this;
    }

    /**
     * Delivery mode to notify signers.
     */
    public function getDeliveryMode(): string
    {
        return $this->deliveryMode;
    }

    /**
     * Delivery mode to notify signers.
     */
    public function setDeliveryMode(string $deliveryMode): self
    {
        $this->deliveryMode = $deliveryMode;

        return $this;
    }

    /**
     * Enable an ordered workflow, each signer will be requested to sign in a sequential order.
     */
    public function getOrderedSigners(): bool
    {
        return $this->orderedSigners;
    }

    /**
     * Enable an ordered workflow, each signer will be requested to sign in a sequential order.
     */
    public function setOrderedSigners(bool $orderedSigners): self
    {
        $this->orderedSigners = $orderedSigners;

        return $this;
    }

    public function getReminderSettings(): ?SignatureRequestsSignatureRequestIdPatchBodyReminderSettings
    {
        return $this->reminderSettings;
    }

    public function setReminderSettings(?SignatureRequestsSignatureRequestIdPatchBodyReminderSettings $reminderSettings): self
    {
        $this->reminderSettings = $reminderSettings;

        return $this;
    }

    /**
     * tz database format.
     */
    public function getTimezone(): string
    {
        return $this->timezone;
    }

    /**
     * tz database format.
     */
    public function setTimezone(string $timezone): self
    {
        $this->timezone = $timezone;

        return $this;
    }

    public function getEmailCustomNote(): ?string
    {
        return $this->emailCustomNote;
    }

    public function setEmailCustomNote(?string $emailCustomNote): self
    {
        $this->emailCustomNote = $emailCustomNote;

        return $this;
    }

    public function getExpirationDate(): \DateTime
    {
        return $this->expirationDate;
    }

    public function setExpirationDate(\DateTime $expirationDate): self
    {
        $this->expirationDate = $expirationDate;

        return $this;
    }

    public function getExternalId(): ?string
    {
        return $this->externalId;
    }

    public function setExternalId(?string $externalId): self
    {
        $this->externalId = $externalId;

        return $this;
    }

    public function getBrandingId(): ?string
    {
        return $this->brandingId;
    }

    public function setBrandingId(?string $brandingId): self
    {
        $this->brandingId = $brandingId;

        return $this;
    }
}
