<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class SignerCustomText
{
    /**
     * @var string|null
     */
    protected $requestSubject;
    /**
     * @var string|null
     */
    protected $requestBody;
    /**
     * @var string|null
     */
    protected $reminderSubject;
    /**
     * @var string|null
     */
    protected $reminderBody;

    public function getRequestSubject(): ?string
    {
        return $this->requestSubject;
    }

    public function setRequestSubject(?string $requestSubject): self
    {
        $this->requestSubject = $requestSubject;

        return $this;
    }

    public function getRequestBody(): ?string
    {
        return $this->requestBody;
    }

    public function setRequestBody(?string $requestBody): self
    {
        $this->requestBody = $requestBody;

        return $this;
    }

    public function getReminderSubject(): ?string
    {
        return $this->reminderSubject;
    }

    public function setReminderSubject(?string $reminderSubject): self
    {
        $this->reminderSubject = $reminderSubject;

        return $this;
    }

    public function getReminderBody(): ?string
    {
        return $this->reminderBody;
    }

    public function setReminderBody(?string $reminderBody): self
    {
        $this->reminderBody = $reminderBody;

        return $this;
    }
}
