<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class SignatureRequestsSignatureRequestIdSignersSignerIdAuditTrailsGetResponse200
{
    /**
     * @var float
     */
    protected $version;
    /**
     * @var mixed
     */
    protected $signatureRequest;
    /**
     * @var mixed
     */
    protected $sender;
    /**
     * @var mixed
     */
    protected $signer;
    /**
     * @var mixed[]
     */
    protected $documents;
    /**
     * @var mixed
     */
    protected $organization;
    /**
     * @var mixed
     */
    protected $authentication;
    /**
     * @var mixed
     */
    protected $electronicSignatureLevel;

    public function getVersion(): float
    {
        return $this->version;
    }

    public function setVersion(float $version): self
    {
        $this->version = $version;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSignatureRequest()
    {
        return $this->signatureRequest;
    }

    /**
     * @param mixed $signatureRequest
     */
    public function setSignatureRequest($signatureRequest): self
    {
        $this->signatureRequest = $signatureRequest;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSender()
    {
        return $this->sender;
    }

    /**
     * @param mixed $sender
     */
    public function setSender($sender): self
    {
        $this->sender = $sender;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getSigner()
    {
        return $this->signer;
    }

    /**
     * @param mixed $signer
     */
    public function setSigner($signer): self
    {
        $this->signer = $signer;

        return $this;
    }

    /**
     * @return mixed[]
     */
    public function getDocuments(): array
    {
        return $this->documents;
    }

    /**
     * @param mixed[] $documents
     */
    public function setDocuments(array $documents): self
    {
        $this->documents = $documents;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getOrganization()
    {
        return $this->organization;
    }

    /**
     * @param mixed $organization
     */
    public function setOrganization($organization): self
    {
        $this->organization = $organization;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getAuthentication()
    {
        return $this->authentication;
    }

    /**
     * @param mixed $authentication
     */
    public function setAuthentication($authentication): self
    {
        $this->authentication = $authentication;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getElectronicSignatureLevel()
    {
        return $this->electronicSignatureLevel;
    }

    /**
     * @param mixed $electronicSignatureLevel
     */
    public function setElectronicSignatureLevel($electronicSignatureLevel): self
    {
        $this->electronicSignatureLevel = $electronicSignatureLevel;

        return $this;
    }
}
