<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class SignatureRequestActivatedReminderSettings
{
    /**
     * @var float
     */
    protected $intervalInDays;
    /**
     * @var float
     */
    protected $maxOccurrences;

    public function getIntervalInDays(): float
    {
        return $this->intervalInDays;
    }

    public function setIntervalInDays(float $intervalInDays): self
    {
        $this->intervalInDays = $intervalInDays;

        return $this;
    }

    public function getMaxOccurrences(): float
    {
        return $this->maxOccurrences;
    }

    public function setMaxOccurrences(float $maxOccurrences): self
    {
        $this->maxOccurrences = $maxOccurrences;

        return $this;
    }
}
