<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Model;

class SignatureRequestsSignatureRequestIdDocumentsPostBody
{
    /**
     * Binary file.
     *
     * @var string
     */
    protected $file;
    /**
     * @var string
     */
    protected $nature;
    /**
     * @var string|null
     */
    protected $password;
    /**
     * @var mixed|null
     */
    protected $initials;
    /**
     * @var bool|null
     */
    protected $parseAnchors;

    /**
     * Binary file.
     */
    public function getFile(): string
    {
        return $this->file;
    }

    /**
     * Binary file.
     */
    public function setFile(string $file): self
    {
        $this->file = $file;

        return $this;
    }

    public function getNature(): string
    {
        return $this->nature;
    }

    public function setNature(string $nature): self
    {
        $this->nature = $nature;

        return $this;
    }

    public function getPassword(): ?string
    {
        return $this->password;
    }

    public function setPassword(?string $password): self
    {
        $this->password = $password;

        return $this;
    }

    /**
     * @return mixed
     */
    public function getInitials()
    {
        return $this->initials;
    }

    /**
     * @param mixed $initials
     */
    public function setInitials($initials): self
    {
        $this->initials = $initials;

        return $this;
    }

    public function getParseAnchors(): ?bool
    {
        return $this->parseAnchors;
    }

    public function setParseAnchors(?bool $parseAnchors): self
    {
        $this->parseAnchors = $parseAnchors;

        return $this;
    }
}
