<?php

declare(strict_types=1);

/*
 * This file has been auto generated by Jane,
 *
 * Do no edit it directly.
 */

namespace IIYousign\Exception;

class PostDocumentsForbiddenException extends ForbiddenException
{
    public function __construct()
    {
        parent::__construct('Access forbidden');
    }
}
